# Generated by Django 4.0.1 on 2022-06-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='タスク名')),
                ('done', models.BooleanField(default=False, verbose_name='完了')),
                ('note', models.TextField(blank=True, help_text='補足説明')),
            ],
            options={
                'verbose_name': 'タスク',
                'verbose_name_plural': 'タスク',
            },
        ),
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='リスト名')),
                ('updated', models.DateField(auto_now=True, verbose_name='最終更新日')),
                ('tasks', models.ManyToManyField(help_text='タスク一覧', to='todo.Task')),
            ],
            options={
                'verbose_name': 'Todoリスト',
                'verbose_name_plural': 'Todoリスト',
            },
        ),
    ]
